# Generated by Django 4.0 on 2022-05-05 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('Location', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_function', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('key_skills', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('vacancies', models.IntegerField()),
                ('job_description', models.TextField()),
                ('experience', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('salary', models.IntegerField()),
                ('educational_qualification', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('company', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('logo', models.FileField(upload_to='logo')),
                ('address', models.CharField(help_text='enter within 100 charecter', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
