# Generated by Django 4.0 on 2022-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
