# Generated by Django 4.0 on 2022-05-06 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='logo/'),
        ),
    ]
